version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec

workflows:
  test:
    jobs:
      - test
